from fastapi import APIRouter
from pydantic import BaseModel
from typing import List, Optional

from app.ml import inference as ml

router = APIRouter()

class RecommendationResponse(BaseModel):
    id: str
    equipment: str
    equipmentId: str
    recommendation: str
    reason: str
    savings: int
    confidence: int
    priority: str
    category: str

# Fallback recommendations if the ML layer can't load (keeps UI alive).
_FALLBACK_RECS = [
    {"id": 'rec-1', "equipment": 'CAT 320 Excavator', "equipmentId": 'eq-1',
     "recommendation": 'Relocate to Site Bravo',
     "reason": 'Idle for 14 hours while Site Bravo requires an excavator tomorrow.',
     "savings": 2400, "confidence": 97, "priority": 'high', "category": 'Relocation'},
    {"id": 'rec-2', "equipment": 'CAT 980 Loader', "equipmentId": 'eq-3',
     "recommendation": 'Schedule preventive maintenance',
     "reason": 'Engine hours approaching service interval.',
     "savings": 5800, "confidence": 91, "priority": 'high', "category": 'Maintenance'},
]

@router.get("/recommendations", response_model=List[RecommendationResponse])
async def get_recommendations():
    """
    AI recommendations are now generated by the anomaly-detection model
    (hybrid IsolationForest + RandomForest + CAT-signal rules). Each flagged
    asset becomes an actionable card with a human-readable reason and a
    dollar impact. Bulk orders are excluded from the anomaly features, so a
    legitimate large mining rental is never surfaced as suspicious.
    """
    try:
        recs = ml.anomalies_as_recommendations(limit=8)
        return recs if recs else _FALLBACK_RECS
    except Exception as e:
        print("[ai] recommendations fallback:", e)
        return _FALLBACK_RECS


@router.get("/anomalies")
async def get_anomalies(limit: int = 25, min_severity: Optional[str] = None):
    """Detailed anomaly feed for the Decision Center / anomaly table."""
    try:
        return ml.detect_anomalies(limit=limit, min_severity=min_severity)
    except Exception as e:
        return {"error": str(e), "anomalies": []}


@router.get("/anomalies/summary")
async def get_anomaly_summary():
    """Counts by severity + type + total daily $ exposure."""
    try:
        return ml.anomaly_summary()
    except Exception as e:
        return {"error": str(e), "totalAnomalies": 0}


@router.get("/model-metrics")
async def get_model_metrics():
    """Trained-model performance metrics for an 'AI Model Performance' panel."""
    try:
        return ml.get_metrics()
    except Exception as e:
        return {"error": str(e)}

class CopilotRequest(BaseModel):
    query: str

class CopilotResponse(BaseModel):
    reply: str

@router.post("/copilot", response_model=CopilotResponse)
async def ask_copilot(req: CopilotRequest):
    """
    Conversational copilot answered from LIVE model output. Intent-matches the
    question to anomaly / demand / maintenance / fleet data (8 topics, plus
    natural variations) - no scripted replies.
    """
    try:
        return CopilotResponse(reply=ml.copilot_answer(req.query))
    except Exception as e:
        print("[ai] copilot fallback:", e)
        return CopilotResponse(reply="I can analyze anomalies, demand, maintenance, "
                                     "relocations and fleet status. Try one of the prompts above.")
